import Link from 'next/link';
import Image from 'next/image';
import { ArrowLeft } from 'lucide-react';

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <header className="border-b border-primary-100">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/landing-v4" className="flex items-center gap-3">
            <Image src="/logo.svg" alt="Asciv" width={40} height={20} className="h-5 w-auto" />
            <span className="text-xl font-semibold text-primary-900">Asciv</span>
          </Link>
          <Link
            href="/landing-v4"
            className="flex items-center gap-2 text-sm text-primary-500 hover:text-primary-900 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-16">
        <div className="mb-12">
          <h1 className="text-4xl font-bold text-primary-900 mb-4">Terms of Service</h1>
          <p className="text-primary-500">Last updated: February 1, 2026</p>
        </div>

        <div className="prose prose-primary max-w-none">
          <p className="text-lg text-primary-600 mb-8">
            These Terms of Service ("Terms") govern your use of Asciv. By using our platform,
            you agree to these Terms.
          </p>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-primary-900 mb-4">1. Service Description</h2>
            <p className="text-primary-600 mb-4">
              Asciv is a job evaluation and application preparation platform that provides:
            </p>
            <ul className="list-disc pl-6 text-primary-600 space-y-2">
              <li>AI-powered job matching and analysis</li>
              <li>CV and cover letter generation</li>
              <li>Application pipeline tracking</li>
              <li>Professional profile management</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-primary-900 mb-4">2. Account Registration</h2>
            <ul className="list-disc pl-6 text-primary-600 space-y-2">
              <li>You must be at least 16 years old to create an account.</li>
              <li>You must provide accurate and complete information.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>One person may not maintain multiple accounts.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-primary-900 mb-4">3. Acceptable Use</h2>
            <p className="text-primary-600 mb-4">You agree NOT to:</p>
            <ul className="list-disc pl-6 text-primary-600 space-y-2">
              <li>Use the service for any unlawful purpose</li>
              <li>Submit false or misleading information</li>
              <li>Attempt to reverse-engineer or copy our AI algorithms</li>
              <li>Scrape, harvest, or collect data from our platform</li>
              <li>Interfere with or disrupt the service</li>
              <li>Share your account credentials with others</li>
              <li>Use automated systems to access the service without permission</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-primary-900 mb-4">4. Your Content</h2>
            <h3 className="text-lg font-medium text-primary-800 mt-6 mb-3">4.1 Ownership</h3>
            <p className="text-primary-600 mb-4">
              You retain ownership of all content you submit (profile data, job descriptions, etc.).
              By using Asciv, you grant us a license to process this content to provide our services.
            </p>

            <h3 className="text-lg font-medium text-primary-800 mt-6 mb-3">4.2 Generated Content</h3>
            <p className="text-primary-600 mb-4">
              CVs and cover letters generated by our AI are owned by you. You may use, modify, and
              distribute them as you see fit. We do not claim any rights to generated content.
            </p>

            <h3 className="text-lg font-medium text-primary-800 mt-6 mb-3">4.3 Responsibility</h3>
            <p className="text-primary-600">
              You are responsible for reviewing and verifying all generated content before use.
              AI-generated content may require editing for accuracy and appropriateness.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-primary-900 mb-4">5. AI Services</h2>
            <ul className="list-disc pl-6 text-primary-600 space-y-2">
              <li>AI analysis and generation are provided "as is" without guarantees of accuracy.</li>
              <li>Match scores are estimates based on available information and should not be the sole basis for application decisions.</li>
              <li>Generated documents may require human review and editing.</li>
              <li>You can opt out of AI processing in your account settings.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-primary-900 mb-4">6. Service Availability</h2>
            <p className="text-primary-600">
              We strive to maintain high availability but do not guarantee uninterrupted access.
              We may modify, suspend, or discontinue features with reasonable notice.
              Scheduled maintenance will be communicated in advance when possible.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-primary-900 mb-4">7. Limitation of Liability</h2>
            <p className="text-primary-600 mb-4">
              To the maximum extent permitted by law:
            </p>
            <ul className="list-disc pl-6 text-primary-600 space-y-2">
              <li>Asciv is provided "as is" without warranties of any kind.</li>
              <li>We are not liable for any indirect, incidental, or consequential damages.</li>
              <li>We are not responsible for job application outcomes or employment decisions.</li>
              <li>Our total liability is limited to amounts you paid us (if any) in the past 12 months.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-primary-900 mb-4">8. Indemnification</h2>
            <p className="text-primary-600">
              You agree to indemnify and hold harmless Asciv from any claims, damages, or expenses
              arising from your use of the service, your content, or your violation of these Terms.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-primary-900 mb-4">9. Termination</h2>
            <ul className="list-disc pl-6 text-primary-600 space-y-2">
              <li>You may terminate your account at any time through account settings.</li>
              <li>We may suspend or terminate accounts that violate these Terms.</li>
              <li>Upon termination, your data will be deleted according to our Privacy Policy.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-primary-900 mb-4">10. Changes to Terms</h2>
            <p className="text-primary-600">
              We may update these Terms from time to time. We will notify you of material changes
              via email or through the platform. Continued use after changes constitutes acceptance.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-primary-900 mb-4">11. Governing Law</h2>
            <p className="text-primary-600">
              These Terms are governed by the laws of France. Any disputes will be resolved in the
              courts of Paris, France, unless you are an EU consumer entitled to use local courts.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-semibold text-primary-900 mb-4">12. Contact</h2>
            <p className="text-primary-600">
              For questions about these Terms:
            </p>
            <ul className="list-none text-primary-600 mt-4 space-y-1">
              <li>Email: <a href="mailto:legal@asciv.com" className="text-accent-500 hover:text-accent-600">legal@asciv.com</a></li>
              <li>Contact form: <Link href="/contact" className="text-accent-500 hover:text-accent-600">asciv.com/contact</Link></li>
            </ul>
          </section>
        </div>

        {/* Related Links */}
        <div className="mt-16 pt-8 border-t border-primary-100">
          <h3 className="text-sm font-semibold text-primary-900 mb-4">Related</h3>
          <div className="flex flex-wrap gap-4">
            <Link href="/privacy" className="text-sm text-primary-500 hover:text-primary-900 transition-colors">
              Privacy Policy →
            </Link>
            <Link href="/cookies" className="text-sm text-primary-500 hover:text-primary-900 transition-colors">
              Cookie Policy →
            </Link>
            <Link href="/gdpr" className="text-sm text-primary-500 hover:text-primary-900 transition-colors">
              GDPR →
            </Link>
          </div>
        </div>
      </main>

      {/* Simple Footer */}
      <footer className="border-t border-primary-100 mt-16">
        <div className="max-w-4xl mx-auto px-6 py-8 flex flex-col sm:flex-row justify-between items-center gap-4">
          <p className="text-sm text-primary-400">© 2026 Asciv. All rights reserved.</p>
          <div className="flex items-center gap-6 text-sm">
            <Link href="/privacy" className="text-primary-500 hover:text-primary-900 transition-colors">
              Privacy
            </Link>
            <Link href="/terms" className="text-primary-500 hover:text-primary-900 transition-colors">
              Terms
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
